spring:
  servlet:
    multipart:
      max-file-size: 100MB #单个文件最大
      max-request-size: 100MB #一次请求最大
yuepaijie:
  auth:
    timeoutMinute: 90
aliyun:
  oss:
    endPoint: oss-cn-hongkong.aliyuncs.com
    accessKeyId: LTAI4FzizG9qX1NJgF4urzY3
    accessKeySecret: FMzyCVhaWWh8qI5CevU9DMFfGHvcnN
    bucketNamePublic: yuepaijie-public
    bucketNamePrivate: yuepaijie-private