server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://8.210.157.161:3306/yuepaijie
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/generated/*.xml