package com.yuepaijie.entity;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.userInfoId
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private Long userinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public Account(Long id, Long userinfoid, String account, String password) {
        this.id = id;
        this.userinfoid = userinfoid;
        this.account = account;
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public Account() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.userInfoId
     *
     * @return the value of account.userInfoId
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public Long getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.userInfoId
     *
     * @param userinfoid the value for account.userInfoId
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setUserinfoid(Long userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account
     *
     * @return the value of account.account
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account
     *
     * @param account the value for account.account
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}