package com.yuepaijie.entity;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.id
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.name
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.gender
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.phone
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.province
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.city
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.birthday
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.createtime
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.updatetime
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public UserInfo(Long id, String name, Byte gender, String phone, String province, String city, Date birthday, Date createtime, Date updatetime) {
        this.id = id;
        this.name = name;
        this.gender = gender;
        this.phone = phone;
        this.province = province;
        this.city = city;
        this.birthday = birthday;
        this.createtime = createtime;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public UserInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.id
     *
     * @return the value of userInfo.id
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.id
     *
     * @param id the value for userInfo.id
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.name
     *
     * @return the value of userInfo.name
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.name
     *
     * @param name the value for userInfo.name
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.gender
     *
     * @return the value of userInfo.gender
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.gender
     *
     * @param gender the value for userInfo.gender
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.phone
     *
     * @return the value of userInfo.phone
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.phone
     *
     * @param phone the value for userInfo.phone
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.province
     *
     * @return the value of userInfo.province
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.province
     *
     * @param province the value for userInfo.province
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.city
     *
     * @return the value of userInfo.city
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.city
     *
     * @param city the value for userInfo.city
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.birthday
     *
     * @return the value of userInfo.birthday
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.birthday
     *
     * @param birthday the value for userInfo.birthday
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.createtime
     *
     * @return the value of userInfo.createtime
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.createtime
     *
     * @param createtime the value for userInfo.createtime
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.updatetime
     *
     * @return the value of userInfo.updatetime
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.updatetime
     *
     * @param updatetime the value for userInfo.updatetime
     *
     * @mbg.generated Wed Oct 07 21:04:50 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}