server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://8.210.157.161:3306/yuepaijie?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
redis:
  host: 127.0.0.1
  port: 6379
  password: LvLeEG9bI4aUwfOZ
  pool:
    max-total: 1000
    max-idle: 200
    max-wait-millis: 3000
  test-on-borrow: true
  use-sentinel: false
  database: 0
  timeout: 20000
yuepaijie:
  auth:
    timeoutMinute: 90