server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://8.210.157.161:3306/yuepaijie?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 8.210.157.161
    port: 6379
    max-idle: 20
    max-total: 100
    max-wait-millis: 3000
    password: LvLeEG9bI4aUwfOZ
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
redis:
  host: 8.210.157.161
  port: 6379
  password: LvLeEG9bI4aUwfOZ
  pool:
    max-idle: 200
    max-total: 1000
    max-wait: 30000
  test-on-borrow: true
  use-sentinel: false
  database: 8
  timeout: 20000
yuepaijie:
  auth:
    timeoutMinute: 90